spring:
  datasource:
    username: root
    password: a59964360
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.55.204:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    hikari:
      max-lifetime: 20000
      connection-timeout: 120000

  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
  thymeleaf:
    cache: false  #开发时候禁用掉缓存，方便实时看更新调试    场景：不然更新html build还是看不到更新

  redis:
    host: 101.34.55.204
    password: 547061946
    timeout: 80000

#spring cache
  cache:
    type: redis
    redis:
      time-to-live: 50000 #这里我想热部署，搞一下午  jrebel+devtools 都不行还得重启项目
      #我想到的结论： @Bean是项目启动时候加载进来的！所以得重启项目才会跑@Bean加载配置！不像Demo中Entity直接绑yaml没有代码处理
      #热部署部署代码和配置文件，而这里部署了yaml但是读这个yaml的代码@Bean没变动不会重新去读？

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 不配置逻辑删除了，因为 brand 用改逻辑删除字段
#      logic-delete-field: showStatus # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


server:
  port: 10000

logging:
  level:
    com.zzq.gulimall: debug


# 配置 feign 默认请求时间仅几秒钟，配置请求时间长一些(毫秒)
ribbon:
  ReadTimeOut: 60000
  ConnectTimeOut: 60000

#gulimall:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10

# 编译虽然提示：Loaded classes are up to date. Nothing to reload.   但是热部署成功
com:
  zzq:
    name: zzq
    age: 3
