spring:
  datasource:
    username: root
    password: a59964360
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.55.204:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:   #要配置到 bootstrap
#        file-extension: yaml
#        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-coupon

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #\u6709\u9ED8\u8BA4\u7684 \u5177\u4F53\u770B MybatisPlusProperties
  global-config:
    db-config:
      id-type: auto


server:
  port: 7000

coupon:
  user:
    name: zhangsan
    age: 18