server:
  port: 25000


spring:
  task:
    #\u5B9A\u65F6\u4EFB\u52A1
    scheduling:
      pool:
        size: 5
    #\u5F02\u6B65\u4EFB\u52A1
    execution:
      pool:
        core-size: 5
        max-size: 50
