server:
  port: 9010

spring:
  datasource:
    username: root
    password: a59964360
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.55.204:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#    MQ
  rabbitmq:
    addresses: 101.34.55.204
    virtual-host: /
    #开启发送端确认
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false
  application:
    name: gulimall-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #\u6709\u9ED8\u8BA4\u7684 \u5177\u4F53\u770B MybatisPlusProperties
  global-config:
    db-config:
      id-type: auto

#支付
alipay:
  app-id: 2021000122613236


