# 应用名称
spring:
  application:
    name: gulimall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test-route
          uri: https://www.baidu.com/
          predicates:
            - Query=url,google
        - id: zhihu-route
          uri: https://www.zhihu.com/
          predicates:
            - Query=q,zhihu

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}


      #将主机地址为search.gulimall.com转发至gulimall-search
        - id: gulimall_serach_host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

      #将主机地址为auth.gulimall.com转发至gulimall-auth
        - id: gulimall_auth_host
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com

      #将主机地址为cart.gulimall.com转发至gulimall-cart
        - id: gulimall_cart_host
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

      #将主机地址为order.gulimall.com转发至gulimall-order
        - id: gulimall_order_host
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

      #将主机地址为seckill.gulimall.com转发至gulimall-seckill
        - id: gulimall_seckill_host
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com

      #将主机地址为**.gulimall.com转发至gulimall-product
        - id: gulimall_host
          uri: lb://gulimall-product
          predicates:
            - Host=**.gulimall.com

  ## 前端项目，/api
### http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
### http://localhost:88/api/product/category/list/tree  http://localhost:10000/product/category/list/tree

#logging:
#  level:
#    org.springframework.cloud.gateway: debug


server:
  port: 88

