spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: f614012b-fc1e-4375-bf35-49e26f4b5fbf

    alicloud:
      sms:
        host: https://gyytz.market.alicloudapi.com

server:
  port: 30000